apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec: 
  project: default
  source:
    path: 2-prometheus
    repoURL: https://github.com/jeremy-misola/my-homelab
    targetRevision: HEAD
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
